export const clerkTheme = {
  variables: {
    colorPrimary: "#1B4FD8",
    colorText: "#1A1A1A",
    colorTextSecondary: "#666666",
    colorBackground: "#FFFFFF",
    colorInputBackground: "#F9FAFB",
    colorInputText: "#1A1A1A",
    colorDanger: "#DC2626",
    colorSuccess: "#16A34A",
    colorWarning: "#D97706",
    borderRadius: "0.5rem",
    fontFamily: "inherit",
  },
  elements: {
    rootBox: "shadow-none",
    card: "shadow-sm border border-[#E5E5E5] rounded-xl bg-white",
    headerTitle: "text-[#1A1A1A] font-medium text-xl",
    headerSubtitle: "text-[#666666] text-sm",
    formButtonPrimary: "bg-[#1B4FD8] hover:bg-[#1340B0] transition-colors text-white text-sm font-medium h-10 rounded-lg shadow-sm",
    formFieldInput: "h-10 rounded-lg border border-[#E5E5E5] bg-[#F9FAFB] text-sm px-3 focus:ring-1 focus:ring-[#1B4FD8]/20 focus:border-[#1B4FD8] transition-colors",
    formFieldLabel: "text-sm font-medium text-[#1A1A1A]",
    footerActionLink: "text-[#1B4FD8] hover:underline font-medium",
    dividerLine: "bg-[#E5E5E5]",
    dividerText: "text-[#666666] text-xs",
    socialButtonsBlockButton: "border border-[#E5E5E5] bg-white hover:bg-[#F9FAFB] text-[#1A1A1A] rounded-lg h-10 transition-colors",
    socialButtonsBlockButtonText: "text-sm font-medium",
    identityPreviewEditButton: "text-[#1B4FD8] hover:underline",
  },
};
