"""Initial schema

Revision ID: 0519f21bbb78
Revises: 
Create Date: 2026-07-01 00:26:55.104019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0519f21bbb78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_org_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizaciones_clerk_org_id'), 'organizaciones', ['clerk_org_id'], unique=True)
    op.create_table('expedientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('tipo_instalacion', sa.String(), nullable=False),
    sa.Column('comunidad', sa.String(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('potencia_kw', sa.Float(), nullable=False),
    sa.Column('uso', sa.String(), nullable=False),
    sa.Column('numero_puntos', sa.Integer(), nullable=True),
    sa.Column('modo_recarga', sa.String(), nullable=True),
    sa.Column('acceso_publico', sa.Boolean(), nullable=True),
    sa.Column('ubicacion_irve', sa.String(), nullable=True),
    sa.Column('requiere_nuevo_suministro', sa.Boolean(), nullable=True),
    sa.Column('combustible', sa.String(), nullable=True),
    sa.Column('presion_bar', sa.String(), nullable=True),
    sa.Column('solicita_ayuda', sa.Boolean(), nullable=True),
    sa.Column('plan_tramitacion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tiempo_total_dias', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('tramites_completados', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expedientes_org_id'), 'expedientes', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expedientes_org_id'), table_name='expedientes')
    op.drop_table('expedientes')
    op.drop_index(op.f('ix_organizaciones_clerk_org_id'), table_name='organizaciones')
    op.drop_table('organizaciones')
    # ### end Alembic commands ###
