"""make municipio nullable

Revision ID: 6b37eb0a1b9f
Revises: fb6fce9be8d1
Create Date: 2026-07-26 20:20:19.111498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b37eb0a1b9f'
down_revision: Union[str, Sequence[str], None] = 'fb6fce9be8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expedientes', 'municipio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expedientes', 'municipio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
