"""Add simulacion models

Revision ID: b365d684e87c
Revises: 6b37eb0a1b9f
Create Date: 2026-07-27 10:28:58.580826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b365d684e87c'
down_revision: Union[str, Sequence[str], None] = '6b37eb0a1b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisis_facturas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cups', sa.String(), nullable=True),
    sa.Column('consumo_anual_kwh', sa.Float(), nullable=True),
    sa.Column('potencia_contratada_kw', sa.Float(), nullable=True),
    sa.Column('estado_extraccion', sa.String(), nullable=False),
    sa.Column('datos_raw', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogo_componentes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('coste', sa.Float(), nullable=False),
    sa.Column('fuente_url', sa.String(), nullable=False),
    sa.Column('fecha_verificacion', sa.Date(), nullable=False),
    sa.Column('nivel_verificacion', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estudios_energeticos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analisis_factura_id', sa.UUID(), nullable=True),
    sa.Column('ip_origen', sa.String(), nullable=True),
    sa.Column('resultado_json', sa.JSON(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analisis_factura_id'], ['analisis_facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('estudios_energeticos')
    op.drop_table('catalogo_componentes')
    op.drop_table('analisis_facturas')
    # ### end Alembic commands ###
