"""add tramites_estado_referencia_notas

Revision ID: f322ac0b98a0
Revises: 20d1d6d86896
Create Date: 2026-07-23 17:54:38.587885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f322ac0b98a0'
down_revision: Union[str, Sequence[str], None] = '20d1d6d86896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expedientes', sa.Column('tramites_estado', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('expedientes', sa.Column('referencia_cliente', sa.String(), nullable=True))
    op.add_column('expedientes', sa.Column('notas', sa.String(), nullable=True))
    op.alter_column('expedientes', 'creado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('expedientes', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('organizaciones', 'plan',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::text"))
    op.alter_column('organizaciones', 'creado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizaciones', 'creado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('organizaciones', 'plan',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::text"))
    op.alter_column('expedientes', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('expedientes', 'creado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('expedientes', 'notas')
    op.drop_column('expedientes', 'referencia_cliente')
    op.drop_column('expedientes', 'tramites_estado')
    # ### end Alembic commands ###
