"""add_asistente_tables

Revision ID: fb6fce9be8d1
Revises: a0b0be4235c5
Create Date: 2026-07-26 19:55:44.170684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb6fce9be8d1'
down_revision: Union[str, Sequence[str], None] = 'a0b0be4235c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistente_uso',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mensajes', sa.Integer(), nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), nullable=False),
    sa.Column('tokens_entrada_cache', sa.Integer(), nullable=False),
    sa.Column('tokens_salida', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'fecha', name='uq_asistente_uso_org_fecha')
    )
    op.create_index(op.f('ix_asistente_uso_org_id'), 'asistente_uso', ['org_id'], unique=False)
    op.create_table('asistente_conversaciones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('expediente_id', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistente_conversaciones_org_id'), 'asistente_conversaciones', ['org_id'], unique=False)
    op.create_table('asistente_mensajes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversacion_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('contenido', sa.String(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversacion_id'], ['asistente_conversaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistente_mensajes_conversacion_id'), 'asistente_mensajes', ['conversacion_id'], unique=False)
    op.create_table('asistente_reportes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('mensaje_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('contenido', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mensaje_id'], ['asistente_mensajes.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistente_reportes_mensaje_id'), 'asistente_reportes', ['mensaje_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asistente_reportes_mensaje_id'), table_name='asistente_reportes')
    op.drop_table('asistente_reportes')
    op.drop_index(op.f('ix_asistente_mensajes_conversacion_id'), table_name='asistente_mensajes')
    op.drop_table('asistente_mensajes')
    op.drop_index(op.f('ix_asistente_conversaciones_org_id'), table_name='asistente_conversaciones')
    op.drop_table('asistente_conversaciones')
    op.drop_index(op.f('ix_asistente_uso_org_id'), table_name='asistente_uso')
    op.drop_table('asistente_uso')
    # ### end Alembic commands ###
